name: cogs
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - pytorch-cuda=11.8
  - plyfile
  - python=3.11.5
  - pip
  - pytorch=2.3.0
  - torchvision
  - tqdm
  - pip:
    - opencv-python
    - diffusers
    - transformers
    - scipy
    - matplotlib
    - accelerate
    - rich
    - joblib
    - loguru
    - pytorch_lightning
    - kornia
    - einops
    - open_clip_torch
    - tensorboard
    - ipykernel
    - git+https://github.com/facebookresearch/detectron2.git
  #   - xformers
  #   - pytorch3d